name: Build and Deploy Next.js App to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: "本当にdestroyしても良いですか"
        required: true
        default: "false"
        type: choice
        options:
          - "no"
          - "yes"

jobs:
  build-and-deploy:
    if: github.event.inputs.destroy != 'yes'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN}}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform/infrastracture
          terraform init
      - name: Terraform Plan
        run: |
          cd terraform/infrastracture
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform/infrastracture  
          terraform apply -auto-approve

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install adn Build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/out s3://my-gitops-test-bucket-20250803 --delete

  terraform_destroy:
    if: github.event.inputs.destroy == 'yes'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN}}
          aws-region: ap-northeast-1

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform/infrastracture
          terraform init

      - name: Terraform Destroy
        run: |
          cd terraform/infrastracture
          terraform destroy -auto-approve
